
general.import = [
    "~/.config/alacritty/gruvbox_dark.toml"
]

[window]
opacity = 1
decorations = "Full"
startup_mode = "Maximized"

[font]
normal.family = { family = "Jetbrains Mono", style = "Regular" }
bold.family = { family = "Jetbrains Mono", style = "Bold" }
italic.family = { family = "Jetbrains Mono", style = "Italic" }
bold_italic.family = { family = "Jetbrains Mono", style = "Bold Italic" }

size = 13.0

[mouse]
hide_when_typing = false

[terminal]

[terminal.shell]
program = "zellij"

# [[keyboard.bindings]]
# action = "ToggleFullscreen"
# key = "F"
# mods = "Alt"

