theme = "iceberg-dark"

[editor]
line-number = "relative"
mouse = false
completion-timeout = 5
color-modes = true
rulers = [120]
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false
git-ignore = false


[editor.lsp]
display-progress-messages = true
display-inlay-hints	= true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
